vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO Starfield-Reverse-Engineering/CommonLibSF
  REF 0cf0762600420755451a3c5d6bd9d815bdf55b39
  SHA512 b915ce13e4b6420df33753ff040f1159dabc19e8b7cc16fabf0594eb0fc0080aa93631674a0952913de2bdddddd86fff4b95e620ba5c38c9fe89c35bbb38249b
  HEAD_REF main)
 
set(VCPKG_POLICY_EMPTY_PACKAGE enabled)

set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} /D_ITERATOR_DEBUG_LEVEL=0")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} /D_ITERATOR_DEBUG_LEVEL=0")
vcpkg_configure_cmake(
        SOURCE_PATH "${SOURCE_PATH}"
        PREFER_NINJA
        OPTIONS -DSFSE_BUILD_TESTS=off -DSFSE_SUPPORT_XBYAK=off
)

vcpkg_install_cmake()
vcpkg_cmake_config_fixup(PACKAGE_NAME CommonLibSF CONFIG_PATH lib/cmake)
vcpkg_copy_pdbs()

file(GLOB CMAKE_CONFIGS "${CURRENT_PACKAGES_DIR}/share/CommonLibSF/CommonLibSF/*.cmake")
file(INSTALL ${CMAKE_CONFIGS} DESTINATION "${CURRENT_PACKAGES_DIR}/share/CommonLibSF")

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/share/CommonLibSF/CommonLibSF")

file(
  INSTALL "${SOURCE_PATH}/COPYING"
  DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
  RENAME copyright)
